This is an excercise file for Numpy


In [8]:
myList = [1,2,3,4]

In [1]:
import numpy as np

In [4]:
np.array(myList)

array([1, 2, 3, 4])

In [5]:
myTwoList = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [6]:
np.array(myTwoList)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
np.arange(1,34,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [3]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:

np.random.rand(5)

array([0.66557383, 0.99391601, 0.91656433, 0.06480926, 0.25970209])

In [6]:
np.random.randint(50)

40

In [10]:
myList

[1, 2, 3, 4]

In [11]:
myList.reshape(2,2)

AttributeError: 'list' object has no attribute 'reshape'

In [12]:
x = np.array(myList)

In [13]:
x


array([1, 2, 3, 4])

In [14]:
x.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [15]:
pwd

'C:\\Users\\sgupta34\\Desktop\\ML\\MachineLearning'

#intermediate stuff with Numpy

In [17]:
myArray = np.arange(10,20)

In [18]:
myArray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
myArray[8]

18

#2D array (Video 2)

In [23]:
myTwoDArray = [[1,2,3], [4,5,6],[7,8,9]]

In [29]:
myTwoD = np.array(myTwoDArray)

In [30]:
myTwoD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
myTwoD[:2,1:]

array([[2, 3],
       [5, 6]])

In [32]:
myTwoD[:2, :2]

array([[1, 2],
       [4, 5]])

In [33]:
myTwoD[1:, :2]

array([[4, 5],
       [7, 8]])

In [34]:
myTwoD[1:, 1:]

array([[5, 6],
       [8, 9]])

#Practice yourself

In [2]:
arr = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]])

In [3]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]

In [4]:
temp

array([4., 6., 0., 3.])

In [5]:
arr.T

array([[-1. ,  4. ,  2.6,  3. ],
       [ 2. , -0.5,  0. , -7. ],
       [ 0. ,  6. ,  7. ,  4. ],
       [ 4. ,  0. ,  8. ,  2. ]])

In [6]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [7]:
arr = np.array([1,2,3,56,9])

In [8]:
arr[2,4]

IndexError: too many indices for array

In [9]:
arr([2,4])

TypeError: 'numpy.ndarray' object is not callable

In [10]:
arr[np.array([2,4])]

array([3, 9])

In [11]:
arr[3] == arr[np.array([3])]

array([ True])

In [13]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
x = np.ones((1, 2, 3))

In [15]:
x

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
np.transpose(x, (1, 0, 2)).shape

(2, 1, 3)