In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 


In [22]:
%matplotlib inline

In [23]:
import os 
print(os.listdir())

['.ipynb_checkpoints', 'knn.ipynb', 'Social_Network_Ads.csv']


In [24]:
data = pd.read_csv('Social_Network_Ads.csv')

In [25]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [26]:
#creating to set of our data sets for independent and dependent variables

X = data.iloc[:, [2,3]].values

In [27]:
len(X)

400

In [28]:
y = data.iloc[:, -1].values

In [29]:
# prepare the data for train and test data sets
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [31]:
X_train

array([[    28,  84000],
       [    53, 143000],
       [    35,  55000],
       [    39,  79000],
       [    57,  26000],
       [    26,  35000],
       [    30,  17000],
       [    38,  65000],
       [    37,  75000],
       [    26,  15000],
       [    18,  44000],
       [    24,  27000],
       [    41,  72000],
       [    41,  71000],
       [    45,  79000],
       [    42,  64000],
       [    35,  79000],
       [    18,  86000],
       [    35,  65000],
       [    25,  80000],
       [    57,  74000],
       [    37,  70000],
       [    41,  60000],
       [    38,  61000],
       [    26,  80000],
       [    47,  51000],
       [    22,  18000],
       [    33,  69000],
       [    26,  43000],
       [    29,  80000],
       [    28,  89000],
       [    42, 108000],
       [    35,  22000],
       [    34, 115000],
       [    28,  87000],
       [    46,  32000],
       [    46, 117000],
       [    35,  60000],
       [    50,  88000],
       [    25,  79000],


In [32]:
#feature scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_train)

C:\Users\sgupta34\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\sgupta34\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [33]:
X_train

array([[-0.89315559,  0.40163307],
       [ 1.47047152,  2.16631365],
       [-0.23134   , -0.46575229],
       [ 0.14684033,  0.25208387],
       [ 1.84865185, -1.33313766],
       [-1.08224576, -1.0639491 ],
       [-0.70406543, -1.60232623],
       [ 0.05229525, -0.16665389],
       [-0.04224983,  0.13244451],
       [-1.08224576, -1.66214591],
       [-1.83860644, -0.79476054],
       [-1.27133593, -1.30322782],
       [ 0.3359305 ,  0.04271499],
       [ 0.3359305 ,  0.01280515],
       [ 0.71411084,  0.25208387],
       [ 0.43047559, -0.19656373],
       [-0.23134   ,  0.25208387],
       [-1.83860644,  0.46145276],
       [-0.23134   , -0.16665389],
       [-1.17679085,  0.28199371],
       [ 1.84865185,  0.10253467],
       [-0.04224983, -0.01710469],
       [ 0.3359305 , -0.31620309],
       [ 0.05229525, -0.28629325],
       [-1.08224576,  0.28199371],
       [ 0.90320101, -0.58539166],
       [-1.4604261 , -1.57241639],
       [-0.42043017, -0.04701453],
       [-1.08224576,

In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
classifier = KNeighborsClassifier(n_neighbors=5, p = 2, metric='minkowski')

In [36]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [37]:
#get your predictor
y_predictor = classifier.predict(X_test)

In [38]:
y_predictor

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,