In [1]:
#checking directory

import os
print(os.listdir())

['.ipynb_checkpoints', 'CleanupData.csv', 'dataPreProcessing.ipynb']


In [2]:
import numpy as np
import pandas as pd

In [3]:
#importing datasets using pandas

data = pd.read_csv('CleanupData.csv')

In [4]:
data

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes
5     Delhi  25.0        5800.0              Yes
6    Mumbai   NaN        5200.0               No
7     Delhi  38.0        7900.0              Yes
8  Banglore  40.0        8300.0               No
9     Delhi  27.0        6700.0              Yes

In [5]:
# defining independent and dependent variables 

X = data.iloc[ : , : -1 ].values

In [6]:
#independent variables

X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, nan],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', nan, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [7]:
y = data.iloc[:,3].values

In [8]:
# dependent variables
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [9]:
# handeling our missing data using scikit learn

from sklearn.preprocessing import Imputer


In [10]:
imp = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)

C:\Users\sgupta34\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [11]:
imp.fit(X[:, 1:3])

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [12]:
X[:, 1:3] = imp.transform(X[:, 1:3])

In [13]:
from sklearn.preprocessing import LabelEncoder


In [14]:
labelEncoder_X = LabelEncoder()

In [15]:
X [:, 0] = labelEncoder_X.fit_transform(X[:, 0])

In [16]:
X

array([[1, 34.0, 7200.0],
       [2, 17.0, 4800.0],
       [0, 20.0, 5400.0],
       [2, 28.0, 6100.0],
       [0, 30.0, 6377.777777777777],
       [1, 25.0, 5800.0],
       [2, 28.77777777777778, 5200.0],
       [1, 38.0, 7900.0],
       [0, 40.0, 8300.0],
       [1, 27.0, 6700.0]], dtype=object)

In [17]:
#create dummy matrix for categorical dataset

from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()
np.set_printoptions(suppress=True)
X

C:\Users\sgupta34\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\sgupta34\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[   0.        ,    1.        ,    0.        ,   34.        ,
        7200.        ],
       [   0.        ,    0.        ,    1.        ,   17.        ,
        4800.        ],
       [   1.        ,    0.        ,    0.        ,   20.        ,
        5400.        ],
       [   0.        ,    0.        ,    1.        ,   28.        ,
        6100.        ],
       [   1.        ,    0.        ,    0.        ,   30.        ,
        6377.77777778],
       [   0.        ,    1.        ,    0.        ,   25.        ,
        5800.        ],
       [   0.        ,    0.        ,    1.        ,   28.77777778,
        5200.        ],
       [   0.        ,    1.        ,    0.        ,   38.        ,
        7900.        ],
       [   1.        ,    0.        ,    0.        ,   40.        ,
        8300.        ],
       [   0.        ,    1.        ,    0.        ,   27.        ,
        6700.        ]])

In [18]:
# handle y matrix for categorical data

labelEncoder_y = LabelEncoder()

In [23]:
y = labelEncoder_y.fit_transform(y)

In [24]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [27]:
# prepare the data for trainig and testing
#splitting the data set in two sets one is training set and another is test data set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [28]:
X_train

array([[   0.        ,    0.        ,    1.        ,   17.        ,
        4800.        ],
       [   0.        ,    0.        ,    1.        ,   28.        ,
        6100.        ],
       [   0.        ,    1.        ,    0.        ,   38.        ,
        7900.        ],
       [   1.        ,    0.        ,    0.        ,   30.        ,
        6377.77777778],
       [   0.        ,    1.        ,    0.        ,   25.        ,
        5800.        ],
       [   0.        ,    1.        ,    0.        ,    2.        ,
           3.        ],
       [   1.        ,    0.        ,    0.        ,   40.        ,
        8300.        ],
       [   1.        ,    0.        ,    0.        ,   20.        ,
        5400.        ]])

In [29]:
from sklearn.preprocessing import StandardScaler
Scalar_X = StandardScaler()
X_train = Scalar_X.fit_transform(X_train)

In [30]:
X_train


array([[-0.77459667, -0.77459667,  1.73205081, -0.69963115, -0.32927614],
       [-0.77459667, -0.77459667,  1.73205081,  0.26236168,  0.2159544 ],
       [-0.77459667,  1.29099445, -0.57735027,  1.13690062,  0.97088898],
       [ 1.29099445, -0.77459667, -0.57735027,  0.43726947,  0.33245665],
       [-0.77459667,  1.29099445, -0.57735027,  0.        ,  0.09013197],
       [-0.77459667,  1.29099445, -0.57735027, -2.01143956, -2.3411768 ],
       [ 1.29099445, -0.77459667, -0.57735027,  1.31180841,  1.13865222],
       [ 1.29099445, -0.77459667, -0.57735027, -0.43726947, -0.07763127]])